// <auto-generated />
namespace SS.Mvc.GiftShopApp.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201810162022528_FixModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
