// <auto-generated />
namespace SS.Mvc.GiftShopApp.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modifythenameanddetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modifythenameanddetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201811061743163_Modify the name and detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
